export const masterPIC = [
  "Michael Andrea",
  "Setiawan Jaya Kusuma",
  "Irwan Setiawan",
  "Awit Witarsa",
  "Cintia",
  "Rangga Maulingga",
  "Anton Dharmawirja",
  "Ratih Ulfa Haniifa",
  "Deby Ardani Putri",
  "Berry Anderson",
  "Jevin",
  "Bagus Rizky Basuki",
  "Eva Srihartati Simanulang",
  "Reyza Alvaraby",
  "Shendi Rosyian Dwi Cahya",
  "Nindya Chiara Alamanda",
  "Ade Rusmawan Djiun",
  "Farida",
  "Tata Wijaya",
  "Fredi Mergiana",
  "Romadona Romansyah",
  "Agit Apriadi",
  "Abdulloh Jaelani",
  "Atep Hidayat",
  "Nanie Talitha Tjoeng",
  "Magribah Akbar",
  "Engelyn Wibisono",
  "Wisnu Adji Prasetiyo",
  "Gesty Ariyadi",
  "Rika Faizal Rezza",
  "Muhamad Adri Graha Darajat",
  "Mochamad Fajar",
  "Ajat Sudrajat",
  "Panji Akbar",
  "Muhamad Rizal Maulana",
  "Erlan Suryadinata",
  "Sasangka Bhima Asmara",
  "Andria Fitriani",
  "Bentang Pangger Kawistara",
  "Yadi Mulyadi",
  "Imam Handayana",
  "Muhammad Rivan Riyana",
  "Durrul Adha",
  "Rikky Wahjudi",
  "Renita Nimasari Puteri",
  "Novan Ardianto",
  "Arthika Endah Mahanani",
  "Wardiansyah",
  "Luthfi Indra Muhammad",
  "Salmon Mubarok Putra Pradana",
  "Muhammad Adnan An Najib",
  "Hermas Ahadhi Septiaji",
  "Chandra Angkawijaya",
  "Jesica Cristy Br Ginting",
  "Deni Tri Sutrisna",
  "Veronika Yulianti Regina",
  "Danakirti Tjoeng",
  "Aldi Suhada",
  "Rizky Fitri Astuti",
  "Arie Herdiansyah Ibrahim",
  "Intan Sulistianti",
  "Novia Sri Dewi Ginting",
  "Ratim",
  "Junita Betaria Sianturi",
  "Najma Tasya Ilahy",
  "Kezia Mary Abraham",
  "Faisal Firmansyah",
  "Ludira Tisan Satya Sukmaraja",
  "M. Alfin Huda",
  "Nasrun",
  "Teguh Budianto",
  "Chicko Caesar Ferdinand",
  "Aripan Nugraha Muhamad Ramdan",
  "Danabrata Tjoeng",
  "Fadel Arthagena Fadilah",
  "Faizal Reza Nurzeha",
  "Imelda Juniarta Pardede",
  "Annisa Nurjannah",
  "Rudy Eka Triwantara",
  "Moch Chandra Rinaldi",
  "Zaki Abdul Rohman Muwarid",
  "Calvin Leonardo",
  "Putri Meysha Nabila Fauziyya",
  "M.Rizky Apriansyah",
  "Tito Reza Pahlevy",
  "Sella Malinda",
  "Stella Tri Murti",
  "Herjuno Ndaru Kinasih",
  "Muhammad Rizqy Candra Abady",
  "Rizky Hardinata",
  "Syukri",
  "Rizaldi Muhamad",
  "Farhan Naufal Fadli",
  "Harsono",
  "Maria Yolanda",
  "Asep Lukman Fauzi",
  "Ayub Nastiar",
  "Bernard Panji Sujatmiko",
  "Renaldi Alfiandy",
  "Chrestella Dharmadi",
  "Ilham Rizqi Fadillah",
  "Frederica Michael Putri",
  "Kiki Riski",
  "Riani Nadeak",
  "Anjas Listyawan",
  "Wildiya Balqis",
  "Shieryn Arnetta Yudianto",
  "Ahmad Febriyansyah",
  "Raden Kevin Verrel Julio Ananta",
  "Muhamad Taufik Hidayat",
  "Gabriele Yosefhine Hokky",
  "Anisa Nur Habibah",
  "Nisrina Salma Addina",
  "Mella Rahensa",
  "Tasya Yuni Azzahra",
  "Muhamad Rizki Pebriansyah",
  "Khairunnisa Dwi Mulya",
  "Erwan Setiawan",
  "Fedora Yoshe Juandy",
  "Sri Fatwa Nuraliah",
  "Yuniar Nastiti",
  "Alti Setia Atmana",
  "Zea Fauziah",
  "Afifah Meisyahida",
  "Hilda Epiyanti",
  "Bani Adam Aliandy",
  "Rica Trianjas Setiawan",
  "Okky Ainnur Rachman",
  "Kanitha Welda Meredith",
  "Puja Ridwan Nurohman",
  "Shiuly Suherni",
  "Achmad Sofyan Alfarisyi",
  "Reinhard Daniel Yora Pattiasina",
  "Fransiska Soraya Spumanti Rose Purwantho",
  "Ananda Nabila Yahya",
  "Krisda Feronika M.",
  "Muhammad Malik Ibrahim",
  "Joshua Johan Tjahyana",
  "Permata Mayang Susanny",
  "Agusti Maula Qahfi",
  "Marlev Vito H",
  "Asep Rinal Supratman",
  "Dhifa Aksa Hermawan",
  "Rifqi Ahmad Mustawan",
  "Permata Indah Safira",
  "Michael",
  "Moh. Khoiruddin Rajulaini",
  "Riski Nopa Sopiana",
  "Tri Widya Murti",
  "Lewi Bonar Laoh",
  "Luthfiyah Itsnaeni Shufroh",
  "A Dadan Priatna",
  "Muhamad Julian Permana",
  "Muhamad Zaidan Katsura",
  "Fitria Ningsih",
  "Nurhaliza Chairindah",
  "Nathanael Sony Setiawan",
  "Nafis Raihan Hammam",
  "Miftah Anugrah Munggaran",
  "M Azmi Fawaz",
  "Jamal Mustopa",
  "Febbe Kristianingjati Wibowo",
  "Faiz Azhari",
  "Envry Artanti Duidahayu Putri",
  "Aya Diva Tabita",
  "Zaid Hasballah",
  "Ahmad",
  "Albion Apta Za'im",
  "Monica Adelia",
  "Disan Purwantara",
  "Gisela Wijaya",
  "Asyifa Mutiara Islami",
  "Damar Alam Harianto",
  "Defi Sintabela",
  "Thomas Dida Avrihansyah",
  "Siti Fatimah",
  "Royyan Naufal Fauzan",
  "Angga Lesmana",
  "Caroline Marlene",
  "Florensia Angelica Pasaribu",
  "Wafa Sri Wahyuni Rasyid",
  "Dionisius Christian",
  "Moch. Saddam Zein Zulfikar Iman",
  "Adena Musolih",
  "Dzikri Mauliddio",
  "Ricky Subagja",
  "Andra Satryo Utomo",
  "Prastio Rizkas Wibowo",
  "Desty Chania Arisandy",
  "Melissa Hartono",
  "Tika Kartika",
  "Mohammad Redaffa Naufal",
  "Iman Royyaan Muhammad Sahla Yasir",
  "Ganda Nugraha",
  "Adwil Masdhianri",
  "Achmad Khadiq Aqil",
  "Puji Mesti Rahayu",
  "Radita Aulia Utami",
  "Dwi Putri Pertiwi",
  "Dani Ramdani",
  "Febhy Nurulfitri Ramadhini",
  "Bella Nathalia",
  "Azka Rahadian",
];
